server:
  port: 8081


spring:
  profiles:
    active: dev
  application:
    name: spring-lj-admin
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://192.168.0.70:3307/phl-new-beta?useUnicode=true&characterEncoding=utf8
     username: dba
     password: Yhbj@9989
     type: com.alibaba.druid.pool.DruidDataSource
     # 初始连接数
     initialSize: 5
      # 最小连接池数量
     minIdle: 10
      # 最大连接池数量
     maxActive: 20
      # 配置获取连接等待超时的时间
     maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
     maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false